a = int(input("Enter the number between 1 to 19:"))
def check(a):
    if(a==0):
        print("zero")
    elif(a==1):
        print("one")
    elif(a==2):
        print("two")
    elif(a==3):
        print("three")
    elif(a==4):
        print("four")
    elif(a==5):
        print("five")
    elif(a==6):
        print("six")
    elif(a==7):
        print("seven")
    elif(a==8):
        print("eight")
    elif(a==9):
        print("nine")
    elif(a==10):
        print("ten")
    elif(a==11):
        print("eleven")
    elif(a==12):
        print("twelve")
    elif(a==13):
        print("thirteen")
    elif(a==14):
        print("fourteen")
    elif(a==15):
        print("fifteen")
    elif(a==16):
        print("sixteen")
    elif(a==17):
        print("seventeen")
    elif(a==18):
        print("eighteen")
    else:
        print("nineteen")
check(a)